version: '3'

services:
#  api:
#    container_name: "post-api"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8000:8080
#    environment:
#      DB_USER: sa
#      DB_PASSWORD: password
#      DB_NAME: compose-db
#      DB_HOST: postgres_db
#      DB_PORT: 5432

  db:
    container_name: post_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true